package handlers

import (
	"log/slog"
	"testEffMobile/internal/service"

	"github.com/gin-gonic/gin"
	"gorm.io/gorm"

	_ "testEffMobile/docs" // docs is generated by Swag CLI, you have to import it.

	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

func SetupRoutes(router *gin.Engine, db *gorm.DB, enricher *service.EnricherService, logger *slog.Logger) {

	personHandler := NewPersonHandler(db, enricher, logger)

	api := router.Group("/api/v1")
	{
		api.POST("person", personHandler.CreatePerson)
		api.PATCH("person", personHandler.UpdatePerson)
		api.GET("person/:id", personHandler.GetPersonHandler)
		api.DELETE("person/:id", personHandler.DeletePerson)

		api.GET("people", personHandler.GetPeopleHandler)

	}

	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
}
